### ISSUE TITLE
API : ServingSession is Not Breakfast or Lunch

### ISSUE THREAD

**Issue by zanix** [evanhsu/MMM-TitanSchoolMealMenu#1]
The API for my kids school changed `ServingSession` to "Seamless Summer Breakfast" and "Seamless Summer Lunch" for some reason. This causes the menu to show as "none".

I changed `TitanSchoolsClient.js` line 123 to:

```javscript
const breakfastOrLunch = menuSession.ServingSession.match(/breakfast/i) ? 'breakfast' : 'lunch';
```

And now the menu shows up again.
I didn't submit a PR because this feels more like a hack than a fix.

This is what the API returns now.

![Screenshot-20210927121209-1744x1318](https://user-images.githubusercontent.com/1580378/134963157-6a722342-58f9-46d0-9034-719462fe704d.png)

**Comment by evanhsu** [comment]
Thanks for the heads up on the change to the titank12 api!
I like that your fix is simple and pragmatic.  I think it's totally appropriate for the Magic Mirror to just display "breakfast" or "lunch", rather than try to maintain parity with the full titank12 schema.

I'm going to incorporate your pattern match 👍🏻 
Sorry it took me a year to respond... 😬

**Comment by zanix** [comment]
Thanks, and no problem with how long it took. I guess I was the only one with the issue.
Funnily enough, for this year, they changed it back to just "Breakfast" and "Lunch".

Now that I got your attention, I recall making a couple of other edits to the CSS as it was overwriting some other MM modules I use. I will submit a PR for that soon.
