### ISSUE TITLE
Titan is now Linq Connect and API URL Changed

### ISSUE THREAD

**Issue by zanix** [evanhsu/MMM-TitanSchoolMealMenu#5]
Titan changed both the name of the site (now Linq Connect) and the API URL

The new API URL is
```
https://api.titank12.com/api/
```

Everything else seems to have stayed the same, including district and building IDs.

**Comment by zanix** [comment]
Looks like they chang4e it again to `https://api.linqconnect.com/api`

**Comment by zanix** [comment]
I went ahead and created a PR for this #6

**Comment by evanhsu** [comment]
The old URL looks like it has stopped working (the redirect results in an html response now instead of the desired json response).  The new `https://api.linqconnect.com/api` URL works, but I'm noticing some schema changes that have been introduced as well. Who knew school menus were so complicated...

I've added the additional changes to handle the new response schema in https://github.com/evanhsu/MMM-TitanSchoolMealMenu/pull/7
